Added dotenv and readme improvement resolved #20
italia/verificac19-sdk pull request #21
Opened 2022-01-12 08:16 UTC by nicetomytyuk

Added dotenv import in service.js and changed readme in the way to let the user understand on how to set a custom connection string by using **.env** file.

Removed 16-17-18 from readme as it's repeated in 39-40

2022-01-24 21:16 UTC, astagi requested changes
Awesome @nicetomytyuk! Sorry for my late response, I've been so busy during last days! 

Please merge the main branch and resolve conflicts so I can merge your PR easily :)

2022-01-25 07:54 UTC, nicetomytyuk commented
@astagi just solved em' check it out 🎊

2022-01-28 14:58 UTC, astagi approved these changes

2022-01-28 14:59 UTC, merged

2022-01-28 15:00 UTC, astagi commented
Merged! Thank you @nicetomytyuk 🙌